Feature: check SMAPI Navigation

  Background: User Opens App and Capture Events
    When Capture IOS Events
    When Click On IOS Button ["Feedback"]
    When Capture IOS Events

    Then Validate IOS Element ["x-vf-trace-transaction-id" "SMAPI_Presence"] for event ["UIControl" "UITableView"]

  Scenario: Check 1st navigation event to Feedback
#    Then Validate IOS Element ["event-element" "UITableView"] for event ["UIControl" "UITableView"]
#    Then Validate IOS Element ["event-type" "UIControl"] for event ["UIControl" "UITableView"]
    Then Validate IOS Element ["page-name" "Main Page VC"] for event ["UIControl" "UITableView"]
    Then Validate IOS Element ["subpage-name" "NA"] for event ["UIControl" "UITableView"]
    Then Validate IOS Element ["event-description" "Swiped on Position row : 7, sec: 7,  direction none"] for event ["UIControl" "UITableView"]
    Then Validate IOS Element ["x-vf-app-state" "Foreground"] for event ["UIControl" "UITableView"]
    Then Validate IOS Element ["device-orientation" "Portrait"] for event ["UIControl" "UITableView"]
    Then Validate IOS Element ["x-vf-net-type" "WiFi"] for event ["UIControl" "UITableView"]
    Then Validate IOS Element ["x-vf-user-id" "NA"] for event ["UIControl" "UITableView"]
    Then Validate IOS Element ["x-vf-trace-tid" "NA"] for event ["UIControl" "UITableView"]
    Then Validate IOS Element ["x-vf-net-band" "NA"] for event ["UIControl" "UITableView"]
    Then Validate IOS Element ["x-vf-trace-timestamp" "SMAPI_Presence"] for event ["UIControl" "UITableView"]
    Then Validate IOS Element ["x-vf-trace-session-id" "SMAPI_Presence"] for event ["UIControl" "UITableView"]
    Then Validate IOS Element ["x-vf-trace-transaction-id" "SMAPI_Presence"] for event ["UIControl" "UITableView"]

  Scenario: Check 2nd navigation event to Feedback
#    Then Validate IOS Element ["event-element" "UITableView"] for event ["UIControl" "UITableView"]
#    Then Validate IOS Element ["event-type" "UIControl"] for event ["UIControl" "UITableView"]
    Then Validate IOS Element ["page-name" "UINavigationController"] for event ["UIControl" "UITableView"]
    Then Validate IOS Element ["subpage-name" "NA"] for event ["UIControl" "UITableView"]
    Then Validate IOS Element ["event-description" "SMAPI_Presence"] for event ["UIControl" "UITableView"]
    Then Validate IOS Element ["x-vf-app-state" "Foreground"] for event ["UIControl" "UITableView"]
    Then Validate IOS Element ["device-orientation" "Portrait"] for event ["UIControl" "UITableView"]
    Then Validate IOS Element ["x-vf-net-type" "WiFi"] for event ["UIControl" "UITableView"]
    Then Validate IOS Element ["x-vf-user-id" "NA"] for event ["UIControl" "UITableView"]
    Then Validate IOS Element ["x-vf-trace-tid" "NA"] for event ["UIControl" "UITableView"]
    Then Validate IOS Element ["x-vf-net-band" "NA"] for event ["UIControl" "UITableView"]
    Then Validate IOS Element ["x-vf-trace-timestamp" "SMAPI_Presence"] for event ["UIControl" "UITableView"]
    Then Validate IOS Element ["x-vf-trace-session-id" "SMAPI_Presence"] for event ["UIControl" "UITableView"]
    Then Validate IOS Element ["x-vf-trace-transaction-id" "SMAPI_Presence"] for event ["UIControl" "UITableView"]

  Scenario: Check 3rd navigation event to Feedback
#    Then Validate IOS Element ["event-element" "Load Time"] for event ["Page" "Load Time"]
#    Then Validate IOS Element ["event-type" "Page"] for event ["Page" "Load Time"]
    Then Validate IOS Element ["page-name" "SecLibFramework.WelcomeViewController"] for event ["Page" "Load Time"]
    Then Validate IOS Element ["subpage-name" "NA"] for event ["Page" "Load Time"]
    Then Validate IOS Element ["event-description" "SMAPI_Presence"] for event ["Page" "Load Time"]
    Then Validate IOS Element ["x-vf-app-state" "Foreground"] for event ["Page" "Load Time"]
    Then Validate IOS Element ["device-orientation" "Portrait"] for event ["Page" "Load Time"]
    Then Validate IOS Element ["x-vf-net-type" "WiFi"] for event ["Page" "Load Time"]
    Then Validate IOS Element ["x-vf-user-id" "NA"] for event ["Page" "Load Time"]
    Then Validate IOS Element ["x-vf-trace-tid" "NA"] for event ["Page" "Load Time"]
    Then Validate IOS Element ["x-vf-net-band" "NA"] for event ["Page" "Load Time"]
    Then Validate IOS Element ["x-vf-trace-timestamp" "SMAPI_Presence"] for event ["Page" "Load Time"]
    Then Validate IOS Element ["x-vf-trace-session-id" "SMAPI_Presence"] for event ["Page" "Load Time"]
    Then Validate IOS Element ["x-vf-trace-transaction-id" "SMAPI_Presence"] for event ["Page" "Load Time"]

  Scenario: Check 4th navigation event to Feedback
#    Then Validate IOS Element ["event-element" "Stay Time"] for event ["UIControl" "UITableView"]
#    Then Validate IOS Element ["event-type" "Page"] for event ["UIControl" "UITableView"]
    Then Validate IOS Element ["page-name" "SecLibFramework.WelcomeViewController"] for event ["Page" "Stay Time"]
    Then Validate IOS Element ["subpage-name" "NA"] for event ["Page" "Stay Time"]
    Then Validate IOS Element ["event-description" "SMAPI_Presence"] for event ["Page" "Stay Time"]
    Then Validate IOS Element ["x-vf-app-state" "Foreground"] for event ["Page" "Stay Time"]
    Then Validate IOS Element ["device-orientation" "Portrait"] for event ["Page" "Stay Time"]
    Then Validate IOS Element ["x-vf-net-type" "WiFi"] for event ["Page" "Stay Time"]
    Then Validate IOS Element ["x-vf-user-id" "NA"] for event ["Page" "Stay Time"]
    Then Validate IOS Element ["x-vf-trace-tid" "NA"] for event ["Page" "Stay Time"]
    Then Validate IOS Element ["x-vf-net-band" "NA"] for event ["Page" "Stay Time"]
    Then Validate IOS Element ["x-vf-trace-timestamp" "SMAPI_Presence"] for event ["Page" "Stay Time"]
    Then Validate IOS Element ["x-vf-trace-session-id" "SMAPI_Presence"] for event ["Page" "Stay Time"]
    Then Validate IOS Element ["x-vf-trace-transaction-id" "SMAPI_Presence"] for event ["Page" "Stay Time"]

  Scenario: Check 5th navigation event to Feedback
#    Then Validate IOS Element ["event-element" "Load Time"] for event ["UIControl" "UITableView"]
#    Then Validate IOS Element ["event-type" "Page"] for event ["UIControl" "UITableView"]
    Then Validate IOS Element ["page-name" "UINavigationController"] for event ["Page" "Load Time"]
    Then Validate IOS Element ["subpage-name" "NA"] for event ["Page" "Load Time"]
    Then Validate IOS Element ["event-description" "SMAPI_Presence"] for event ["Page" "Load Time"]
    Then Validate IOS Element ["x-vf-app-state" "Foreground"] for event ["Page" "Load Time"]
    Then Validate IOS Element ["device-orientation" "Portrait"] for event ["Page" "Load Time"]
    Then Validate IOS Element ["x-vf-net-type" "WiFi"] for event ["Page" "Load Time"]
    Then Validate IOS Element ["x-vf-user-id" "NA"] for event ["Page" "Load Time"]
    Then Validate IOS Element ["x-vf-trace-tid" "NA"] for event ["Page" "Load Time"]
    Then Validate IOS Element ["x-vf-net-band" "NA"] for event ["Page" "Load Time"]
    Then Validate IOS Element ["x-vf-trace-timestamp" "SMAPI_Presence"] for event ["Page" "Load Time"]
    Then Validate IOS Element ["x-vf-trace-session-id" "SMAPI_Presence"] for event ["Page" "Load Time"]
    Then Validate IOS Element ["x-vf-trace-transaction-id" "SMAPI_Presence"] for event ["Page" "Load Time"]

  Scenario: Check 1st back navigation event from Feedback
    When Click On IOS Button ["arrow.backward"]
    When Capture IOS Events
#    Then Validate IOS Element ["event-element" "UIBarButton"] for event ["UIControl" "UITableView"]
#    Then Validate IOS Element ["event-type" "UIControl"] for event ["UIControl" "UITableView"]
    Then Validate IOS Element ["page-name" "SecLibFramework.FeedbackViewController"] for event ["UIControl" "UIBarButton"]
    Then Validate IOS Element ["subpage-name" "NA"] for event ["UIControl" "UIBarButton"]
    Then Validate IOS Element ["event-description" "NA"] for event ["UIControl" "UIBarButton"]
    Then Validate IOS Element ["x-vf-app-state" "Foreground"] for event ["UIControl" "UIBarButton"]
    Then Validate IOS Element ["device-orientation" "Portrait"] for event ["UIControl" "UIBarButton"]
    Then Validate IOS Element ["x-vf-net-type" "WiFi"] for event ["UIControl" "UIBarButton"]
    Then Validate IOS Element ["x-vf-user-id" "NA"] for event ["UIControl" "UIBarButton"]
    Then Validate IOS Element ["x-vf-trace-tid" "NA"] for event ["UIControl" "UIBarButton"]
    Then Validate IOS Element ["x-vf-net-band" "NA"] for event ["UIControl" "UIBarButton"]
    Then Validate IOS Element ["x-vf-trace-timestamp" "SMAPI_Presence"] for event ["UIControl" "UIBarButton"]
    Then Validate IOS Element ["x-vf-trace-session-id" "SMAPI_Presence"] for event ["UIControl" "UIBarButton"]
    Then Validate IOS Element ["x-vf-trace-transaction-id" "SMAPI_Presence"] for event ["UIControl" "UIBarButton"]

  Scenario: Check 2nd back navigation event from Feedback
    When Click On IOS Button ["arrow.backward"]
    When Capture IOS Events
#    Then Validate IOS Element ["event-element" "Stay Time"] for event ["UIControl" "UITableView"]
#    Then Validate IOS Element ["event-type" "Page"] for event ["UIControl" "UITableView"]
    Then Validate IOS Element ["page-name" "UINavigationController"] for event ["Page" "Stay Time"]
    Then Validate IOS Element ["subpage-name" "NA"] for event ["Page" "Stay Time"]
    Then Validate IOS Element ["event-description" "SMAPI_Presence"] for event ["Page" "Stay Time"]
    Then Validate IOS Element ["x-vf-app-state" "Foreground"] for event ["Page" "Stay Time"]
    Then Validate IOS Element ["device-orientation" "Portrait"] for event ["Page" "Stay Time"]
    Then Validate IOS Element ["x-vf-net-type" "WiFi"] for event ["Page" "Stay Time"]
    Then Validate IOS Element ["x-vf-user-id" "NA"] for event ["Page" "Stay Time"]
    Then Validate IOS Element ["x-vf-trace-tid" "NA"] for event ["Page" "Stay Time"]
    Then Validate IOS Element ["x-vf-net-band" "NA"] for event ["Page" "Stay Time"]
    Then Validate IOS Element ["x-vf-trace-timestamp" "SMAPI_Presence"] for event ["Page" "Stay Time"]
    Then Validate IOS Element ["x-vf-trace-session-id" "SMAPI_Presence"] for event ["Page" "Stay Time"]
    Then Validate IOS Element ["x-vf-trace-transaction-id" "SMAPI_Presence"] for event ["Page" "Stay Time"]

  Scenario: Check 3rd back navigation event from Feedback
    When Click On IOS Button ["arrow.backward"]
    When Capture IOS Events
#    Then Validate IOS Element ["event-element" "Stay Time"] for event ["UIControl" "UITableView"]
#    Then Validate IOS Element ["event-type" "Page"] for event ["UIControl" "UITableView"]
    Then Validate IOS Element ["page-name" "SecLibFramework.FeedbackViewController"] for event ["Page" "Stay Time"]
    Then Validate IOS Element ["subpage-name" "NA"] for event ["Page" "Stay Time"]
    Then Validate IOS Element ["event-description" "SMAPI_Presence"] for event ["Page" "Stay Time"]
    Then Validate IOS Element ["x-vf-app-state" "Foreground"] for event ["Page" "Stay Time"]
    Then Validate IOS Element ["device-orientation" "Portrait"] for event ["Page" "Stay Time"]
    Then Validate IOS Element ["x-vf-net-type" "WiFi"] for event ["Page" "Stay Time"]
    Then Validate IOS Element ["x-vf-user-id" "NA"] for event ["Page" "Stay Time"]
    Then Validate IOS Element ["x-vf-trace-tid" "NA"] for event ["Page" "Stay Time"]
    Then Validate IOS Element ["x-vf-net-band" "NA"] for event ["Page" "Stay Time"]
    Then Validate IOS Element ["x-vf-trace-timestamp" "SMAPI_Presence"] for event ["Page" "Stay Time"]
    Then Validate IOS Element ["x-vf-trace-session-id" "SMAPI_Presence"] for event ["Page" "Stay Time"]
    Then Validate IOS Element ["x-vf-trace-transaction-id" "SMAPI_Presence"] for event ["Page" "Stay Time"]
