Feature: HomePageWeb

  Background: Open Demo Website
    When user open localHost:3000
    When Capture Web Events

  Scenario: Compare Page-load events1
    #UI Custom event
    Then Compare Parameter ["x-vf-user-id" "NA" 0]
    Then Compare Parameter ["device-orientation" "Landscape" 0]
    Then Compare Parameter ["x-vf-net-band" "NA" 0]
    Then Compare Parameter ["x-vf-net-type" "NA" 0]
    Then Compare Parameter ["x-vf-trace-subject-region" "NA" 0]
    Then Compare Parameter ["event-type" "UICustom" 0]
    Then Compare Parameter ["event-element" "testelemen" 0]
    Then Compare Parameter ["event-description" "testdescription" 0]
    Then Compare Parameter ["page-name" "testonPage" 0]
    Then Compare Parameter ["subpage-name" "NA" 0]
    Then Compare Parameter ["x-vf-trace-source" "js:com.vodafone.lib.sec.smapiweb" 0]
    Then Compare Parameter ["x-vf-trace-source-version" "smapi-web-test" 0]
    Then Compare Parameter ["x-vf-custom-authorization-id" "smapi-web-test" 0]
    Then Compare Parameter ["x-vf-custom-test1" "teszt1customjson" 0]
    Then Compare Parameter ["x-vf-custom-test2" "teszt2customjson" 0]
    #UI Custom-Component event
  Scenario: Compare Page-load events2
    Then Compare Parameter ["x-vf-user-id" "NA" 1]
    Then Compare Parameter ["device-orientation" "Landscape" 1]
    Then Compare Parameter ["x-vf-net-band" "NA" 1]
    Then Compare Parameter ["x-vf-net-type" "NA" 1]
    Then Compare Parameter ["x-vf-trace-subject-region" "NA" 1]
    Then Compare Parameter ["event-type" "UICustom" 1]
    Then Compare Parameter ["event-element" "Component" 1]
    Then Compare Parameter ["event-description" "{\\" 1]
    Then Compare Parameter ["TermAndCondition\\" "3.0\\" 1]
    Then Compare Parameter ["Billing\\" "4.0\\" 1]

  Scenario: Compare Page-load events3
#Page loaded event
    Then Compare Parameter ["x-vf-user-id" "NA" 2]
    Then Compare Parameter ["device-orientation" "Landscape" 2]
    Then Compare Parameter ["x-vf-net-band" "NA" 2]
    Then Compare Parameter ["x-vf-net-type" "NA" 2]
    Then Compare Parameter ["x-vf-trace-subject-region" "NA" 2]
    Then Compare Parameter ["event-type" "Page" 2]
    Then Compare Parameter ["event-element" "page-loaded" 2]
   # Then Compare Parameter ["event-description" "1.838 sec" 2]
    Then Compare Parameter ["page-name" "BootsApp | Home-http://localhost:3000/" 2]
    Then Compare Parameter ["subpage-name" "NA" 2]
    Then Compare Parameter ["x-vf-trace-source" "js:com.vodafone.lib.sec.smapiweb" 2]
    Then Compare Parameter ["x-vf-trace-source-version" "smapi-web-test" 2]
    Then Compare Parameter ["x-vf-custom-authorization-id" "smapi-web-test" 2]
    Then Compare Parameter ["x-vf-trace-application-name" "localhost" 2]
    Then Compare Parameter ["seclib-client-version" "6.2.1" 2]
    Then Compare Parameter ["x-vf-trace-locale" "en-US" 2]
    Then Compare Parameter ["x-vf-trace-network-bearer" "4G" 2]
    Then Compare Parameter ["x-vf-trace-os-name" "Windows" 2]
    Then Compare Parameter ["x-vf-trace-os-version" "NT 4.0" 2]
    Then Compare Parameter ["x-vf-trace-mcc" "NA" 2]
    Then Compare Parameter ["x-vf-trace-mnc" "NA" 2]
    Then Compare Parameter ["x-vf-trace-platform" "JS" 2]

  Scenario: Compare Page-dom-loaded event
    Then Compare Parameter ["x-vf-user-id" "NA" 3]
    Then Compare Parameter ["device-orientation" "Landscape" 3]
    Then Compare Parameter ["x-vf-net-band" "NA" 3]
    Then Compare Parameter ["x-vf-net-type" "NA" 3]
    Then Compare Parameter ["x-vf-trace-subject-region" "NA" 3]
    Then Compare Parameter ["event-type" "Page" 3]
    Then Compare Parameter ["event-element" "page-dom-loaded" 3]
    Then Compare Parameter ["page-name" "BootsApp | Home-http://localhost:3000/" 3]
    Then Compare Parameter ["subpage-name" "NA" 3]
    Then Compare Parameter ["x-vf-trace-source" "js:com.vodafone.lib.sec.smapiweb" 3]
    Then Compare Parameter ["x-vf-trace-source-version" "smapi-web-test" 3]
    Then Compare Parameter ["x-vf-custom-authorization-id" "smapi-web-test" 3]
    Then Compare Parameter ["x-vf-trace-application-name" "localhost" 3]
    Then Compare Parameter ["seclib-client-version" "6.2.1" 3]
    Then Compare Parameter ["x-vf-trace-locale" "en-US" 3]
    Then Compare Parameter ["x-vf-trace-network-bearer" "4G" 3]
    Then Compare Parameter ["x-vf-trace-os-name" "Windows" 3]
    Then Compare Parameter ["x-vf-trace-os-version" "NT 4.0" 3]
    Then Compare Parameter ["x-vf-trace-mcc" "NA" 3]
    Then Compare Parameter ["x-vf-trace-mnc" "NA" 3]
    Then Compare Parameter ["x-vf-trace-platform" "JS" 3]

  Scenario: Compare Page-dom-loaded event
    Then Compare Parameter ["x-vf-user-id" "NA" 4]
    Then Compare Parameter ["device-orientation" "Landscape" 4]
    Then Compare Parameter ["x-vf-net-band" "NA" 4]
    Then Compare Parameter ["x-vf-net-type" "NA" 4]
    Then Compare Parameter ["x-vf-trace-subject-region" "NA" 4]
    Then Compare Parameter ["event-type" "Page" 4]
    Then Compare Parameter ["event-element" "soft-navigation (asd)" 4]
    Then Compare Parameter ["page-name" "BootsApp | Home-http://localhost:3000/" 4]
    Then Compare Parameter ["subpage-name" "NA" 4]
    Then Compare Parameter ["x-vf-trace-source" "js:com.vodafone.lib.sec.smapiweb" 4]
    Then Compare Parameter ["x-vf-trace-source-version" "smapi-web-test" 4]
    Then Compare Parameter ["x-vf-custom-authorization-id" "smapi-web-test" 4]
    Then Compare Parameter ["x-vf-trace-application-name" "localhost" 4]
    Then Compare Parameter ["seclib-client-version" "6.2.1" 4]
    Then Compare Parameter ["x-vf-trace-locale" "en-US" 4]
    Then Compare Parameter ["x-vf-trace-network-bearer" "4G" 4]
    Then Compare Parameter ["x-vf-trace-os-name" "Windows" 4]
    Then Compare Parameter ["x-vf-trace-os-version" "NT 4.0" 4]
    Then Compare Parameter ["x-vf-trace-mcc" "NA" 4]
    Then Compare Parameter ["x-vf-trace-mnc" "NA" 4]
    Then Compare Parameter ["x-vf-trace-platform" "JS" 4]




  Scenario: Check UI Control event when clicking on "Change Storage Type"
    When Click Change Storage Type
    And Capture Web Events
    Then Compare Parameter ["event-description" "Change Storage Type" 5]
    Then Compare Parameter ["x-vf-user-id" "NA" 5]
    Then Compare Parameter ["device-orientation" "Landscape" 5]
    Then Compare Parameter ["x-vf-net-band" "NA" 5]
    Then Compare Parameter ["x-vf-net-type" "NA" 5]
    Then Compare Parameter ["x-vf-trace-subject-region" "NA" 5]
    Then Compare Parameter ["event-type" "UIControl" 5]
    Then Compare Parameter ["event-element" "BUTTON - submit" 5]
    Then Compare Parameter ["page-name" "BootsApp | Home-http://localhost:3000/" 5]
    Then Compare Parameter ["subpage-name" "NA" 5]
    Then Compare Parameter ["x-vf-trace-source" "js:com.vodafone.lib.sec.smapiweb" 5]
    Then Compare Parameter ["x-vf-trace-source-version" "smapi-web-test" 5]
    Then Compare Parameter ["x-vf-custom-authorization-id" "smapi-web-test" 5]
    Then Compare Parameter ["x-vf-trace-application-name" "localhost" 5]
    Then Compare Parameter ["seclib-client-version" "6.2.1" 5]
    Then Compare Parameter ["x-vf-trace-locale" "en-US" 5]
    Then Compare Parameter ["x-vf-trace-network-bearer" "4G" 5]
    Then Compare Parameter ["x-vf-trace-os-name" "Windows" 5]
    Then Compare Parameter ["x-vf-trace-os-version" "NT 4.0" 5]
    Then Compare Parameter ["x-vf-trace-mcc" "NA" 2]
    Then Compare Parameter ["x-vf-trace-mnc" "NA" 5]
    Then Compare Parameter ["x-vf-trace-platform" "JS" 5]


  Scenario: Check UI Control event when clicking on "MSISDN - 1234567890" button
    When Click on First MSISDN button
    And Capture Web Events
    Then Compare Parameter ["event-description" "MASKEDMSISDN0" 5]
    Then Compare Parameter ["x-vf-user-id" "NA" 5]
    Then Compare Parameter ["device-orientation" "Landscape" 5]
    Then Compare Parameter ["x-vf-net-band" "NA" 5]
    Then Compare Parameter ["x-vf-net-type" "NA" 5]
    Then Compare Parameter ["x-vf-trace-subject-region" "NA" 5]
    Then Compare Parameter ["event-type" "UIControl" 5]
    Then Compare Parameter ["event-element" "BUTTON - submit" 5]
    Then Compare Parameter ["page-name" "BootsApp | Home-http://localhost:3000/" 5]
    Then Compare Parameter ["subpage-name" "NA" 5]
    Then Compare Parameter ["x-vf-trace-source" "js:com.vodafone.lib.sec.smapiweb" 5]
    Then Compare Parameter ["x-vf-trace-source-version" "smapi-web-test" 5]
    Then Compare Parameter ["x-vf-custom-authorization-id" "smapi-web-test" 5]
    Then Compare Parameter ["x-vf-trace-application-name" "localhost" 5]
    Then Compare Parameter ["seclib-client-version" "6.2.1" 5]
    Then Compare Parameter ["x-vf-trace-locale" "en-US" 5]
    Then Compare Parameter ["x-vf-trace-network-bearer" "4G" 5]
    Then Compare Parameter ["x-vf-trace-os-name" "Windows" 5]
    Then Compare Parameter ["x-vf-trace-os-version" "NT 4.0" 5]
    Then Compare Parameter ["x-vf-trace-mcc" "NA" 2]
    Then Compare Parameter ["x-vf-trace-mnc" "NA" 5]
    Then Compare Parameter ["x-vf-trace-platform" "JS" 5]

  Scenario: Check UI Control event when clicking on "NOT MSISDN 12345NOT6789" button
    When Click on Second MSISDN button
    And Capture Web Events
    Then Compare Parameter ["event-description" "NOT MSISDN - 12345NOT67890" 5]
    Then Compare Parameter ["x-vf-user-id" "NA" 5]
    Then Compare Parameter ["device-orientation" "Landscape" 5]
    Then Compare Parameter ["x-vf-net-band" "NA" 5]
    Then Compare Parameter ["x-vf-net-type" "NA" 5]
    Then Compare Parameter ["x-vf-trace-subject-region" "NA" 5]
    Then Compare Parameter ["event-type" "UIControl" 5]
    Then Compare Parameter ["event-element" "BUTTON - submit" 5]
    Then Compare Parameter ["page-name" "BootsApp | Home-http://localhost:3000/" 5]
    Then Compare Parameter ["subpage-name" "NA" 5]
    Then Compare Parameter ["x-vf-trace-source" "js:com.vodafone.lib.sec.smapiweb" 5]
    Then Compare Parameter ["x-vf-trace-source-version" "smapi-web-test" 5]
    Then Compare Parameter ["x-vf-custom-authorization-id" "smapi-web-test" 5]
    Then Compare Parameter ["x-vf-trace-application-name" "localhost" 5]
    Then Compare Parameter ["seclib-client-version" "6.2.1" 5]
    Then Compare Parameter ["x-vf-trace-locale" "en-US" 5]
    Then Compare Parameter ["x-vf-trace-network-bearer" "4G" 5]
    Then Compare Parameter ["x-vf-trace-os-name" "Windows" 5]
    Then Compare Parameter ["x-vf-trace-os-version" "NT 4.0" 5]
    Then Compare Parameter ["x-vf-trace-mcc" "NA" 2]
    Then Compare Parameter ["x-vf-trace-mnc" "NA" 5]
    Then Compare Parameter ["x-vf-trace-platform" "JS" 5]



    #MSISDN -- with soft navigation
  Scenario: Check UI Control event when clicking on "MSISDN" button
    When Click on Third MSISDN button
    And Capture Web Events
    Then Compare Parameter ["event-description" "MSISDN (URL: http://localhost:3000/#/MASKEDMSISDN0)" 5]
    Then Compare Parameter ["x-vf-user-id" "NA" 5]
    Then Compare Parameter ["device-orientation" "Landscape" 5]
    Then Compare Parameter ["x-vf-net-band" "NA" 5]
    Then Compare Parameter ["x-vf-net-type" "NA" 5]
    Then Compare Parameter ["x-vf-trace-subject-region" "NA" 5]
    Then Compare Parameter ["event-type" "UIControl" 5]
    Then Compare Parameter ["event-element" "A - a" 5]
    Then Compare Parameter ["page-name" "BootsApp | Home-http://localhost:3000/" 5]
    Then Compare Parameter ["subpage-name" "NA" 5]
    Then Compare Parameter ["x-vf-trace-source" "js:com.vodafone.lib.sec.smapiweb" 5]
    Then Compare Parameter ["x-vf-trace-source-version" "smapi-web-test" 5]
    Then Compare Parameter ["x-vf-custom-authorization-id" "smapi-web-test" 5]
    Then Compare Parameter ["x-vf-trace-application-name" "localhost" 5]
    Then Compare Parameter ["seclib-client-version" "6.2.1" 5]
    Then Compare Parameter ["x-vf-trace-locale" "en-US" 5]
    Then Compare Parameter ["x-vf-trace-network-bearer" "4G" 5]
    Then Compare Parameter ["x-vf-trace-os-name" "Windows" 5]
    Then Compare Parameter ["x-vf-trace-os-version" "NT 4.0" 5]
    Then Compare Parameter ["x-vf-trace-mcc" "NA" 5]
    Then Compare Parameter ["x-vf-trace-mnc" "NA" 5]
    Then Compare Parameter ["x-vf-trace-platform" "JS" 5]

  Scenario: Check Soft Navigation event when clicking on "MSISDN" button
    When Click on Third MSISDN button
    And Capture Web Events
    Then Compare Parameter ["event-description" "NA" 6]
    Then Compare Parameter ["x-vf-user-id" "NA" 6]
    Then Compare Parameter ["device-orientation" "Landscape" 6]
    Then Compare Parameter ["x-vf-net-band" "NA" 6]
    Then Compare Parameter ["x-vf-net-type" "NA" 6]
    Then Compare Parameter ["x-vf-trace-subject-region" "NA" 6]
    Then Compare Parameter ["event-type" "Page" 6]
    Then Compare Parameter ["event-element" "soft-navigation" 6]
    Then Compare Parameter ["page-name" "BootsApp | Home-http://localhost:3000/#/1234567890" 6]
    Then Compare Parameter ["subpage-name" "NA" 6]
    Then Compare Parameter ["x-vf-trace-source" "js:com.vodafone.lib.sec.smapiweb" 6]
    Then Compare Parameter ["x-vf-trace-source-version" "smapi-web-test" 6]
    Then Compare Parameter ["x-vf-custom-authorization-id" "smapi-web-test" 6]
    Then Compare Parameter ["x-vf-trace-application-name" "localhost" 6]
    Then Compare Parameter ["seclib-client-version" "6.2.1" 6]
    Then Compare Parameter ["x-vf-trace-locale" "en-US" 6]
    Then Compare Parameter ["x-vf-trace-network-bearer" "4G" 6]
    Then Compare Parameter ["x-vf-trace-os-name" "Windows" 6]
    Then Compare Parameter ["x-vf-trace-os-version" "NT 4.0" 6]
    Then Compare Parameter ["x-vf-trace-mcc" "NA" 6]
    Then Compare Parameter ["x-vf-trace-mnc" "NA" 6]
    Then Compare Parameter ["x-vf-trace-platform" "JS" 6]


#NOT MSISDN with soft navigation
  Scenario: Check UI Control event when clicking on "NOT MSISDN" button
    When Click on the fourth MSISDN button
    And Capture Web Events
    Then Compare Parameter ["event-description" "NOT MSISDN (URL: http://localhost:3000/#/12345NOT67890)" 5]
    Then Compare Parameter ["x-vf-user-id" "NA" 5]
    Then Compare Parameter ["device-orientation" "Landscape" 5]
    Then Compare Parameter ["x-vf-net-band" "NA" 5]
    Then Compare Parameter ["x-vf-net-type" "NA" 5]
    Then Compare Parameter ["x-vf-trace-subject-region" "NA" 5]
    Then Compare Parameter ["event-type" "UIControl" 5]
    Then Compare Parameter ["event-element" "A - a" 5]
    Then Compare Parameter ["page-name" "BootsApp | Home-http://localhost:3000/" 5]
    #"BootsApp | Home-http://localhost:3000/#/1234567890"
    Then Compare Parameter ["subpage-name" "NA" 5]
    Then Compare Parameter ["x-vf-trace-source" "js:com.vodafone.lib.sec.smapiweb" 5]
    Then Compare Parameter ["x-vf-trace-source-version" "smapi-web-test" 5]
    Then Compare Parameter ["x-vf-custom-authorization-id" "smapi-web-test" 5]
    Then Compare Parameter ["x-vf-trace-application-name" "localhost" 5]
    Then Compare Parameter ["seclib-client-version" "6.2.1" 5]
    Then Compare Parameter ["x-vf-trace-locale" "en-US" 5]
    Then Compare Parameter ["x-vf-trace-network-bearer" "4G" 5]
    Then Compare Parameter ["x-vf-trace-os-name" "Windows" 5]
    Then Compare Parameter ["x-vf-trace-os-version" "NT 4.0" 5]
    Then Compare Parameter ["x-vf-trace-mcc" "NA" 2]
    Then Compare Parameter ["x-vf-trace-mnc" "NA" 5]
    Then Compare Parameter ["x-vf-trace-platform" "JS" 5]

#NOT MSISDN soft naviagation
  Scenario: Check Soft Navigation event when clicking on "NOT_MSISDN" button
    When Click on the fourth MSISDN button
    And Capture Web Events
    Then Compare Parameter ["event-description" "NA" 6]
    Then Compare Parameter ["x-vf-user-id" "NA" 6]
    Then Compare Parameter ["device-orientation" "Landscape" 6]
    Then Compare Parameter ["x-vf-net-band" "NA" 6]
    Then Compare Parameter ["x-vf-net-type" "NA" 6]
    Then Compare Parameter ["x-vf-trace-subject-region" "NA" 6]
    Then Compare Parameter ["event-type" "Page" 6]
    Then Compare Parameter ["event-element" "soft-navigation" 6]
    Then Compare Parameter ["page-name" "BootsApp | Home-http://localhost:3000/#/12345NOT67890" 6]
    Then Compare Parameter ["subpage-name" "NA" 6]
    Then Compare Parameter ["x-vf-trace-source" "js:com.vodafone.lib.sec.smapiweb" 6]
    Then Compare Parameter ["x-vf-trace-source-version" "smapi-web-test" 6]
    Then Compare Parameter ["x-vf-custom-authorization-id" "smapi-web-test" 6]
    Then Compare Parameter ["x-vf-trace-application-name" "localhost" 6]
    Then Compare Parameter ["seclib-client-version" "6.2.1" 6]
    Then Compare Parameter ["x-vf-trace-locale" "en-US" 6]
    Then Compare Parameter ["x-vf-trace-network-bearer" "4G" 6]
    Then Compare Parameter ["x-vf-trace-os-name" "Windows" 6]
    Then Compare Parameter ["x-vf-trace-os-version" "NT 4.0" 6]
    Then Compare Parameter ["x-vf-trace-mcc" "NA" 6]
    Then Compare Parameter ["x-vf-trace-mnc" "NA" 6]
    Then Compare Parameter ["x-vf-trace-platform" "JS" 6]


  Scenario: Check UI Component event when clicking on "Get Started"
    When Click on Get Started
    And Capture Web Events
    Then Compare Parameter ["event-description" "Get Started (URL: http://localhost:3000/login.html)" 5]
    Then Compare Parameter ["x-vf-user-id" "NA" 5]
    Then Compare Parameter ["device-orientation" "Landscape" 5]
    Then Compare Parameter ["x-vf-net-band" "NA" 5]
    Then Compare Parameter ["x-vf-net-type" "NA" 5]
    Then Compare Parameter ["x-vf-trace-subject-region" "NA" 5]
    Then Compare Parameter ["event-type" "UIControl" 5]
    Then Compare Parameter ["event-element" "A - a" 5]
    Then Compare Parameter ["page-name" "BootsApp | Home-http://localhost:3000/" 5]
    Then Compare Parameter ["subpage-name" "NA" 5]
    Then Compare Parameter ["x-vf-trace-source" "js:com.vodafone.lib.sec.smapiweb" 5]
    Then Compare Parameter ["x-vf-trace-source-version" "smapi-web-test" 5]
    Then Compare Parameter ["x-vf-custom-authorization-id" "smapi-web-test" 5]
    Then Compare Parameter ["x-vf-trace-application-name" "localhost" 5]
    Then Compare Parameter ["seclib-client-version" "6.2.1" 5]
    Then Compare Parameter ["x-vf-trace-locale" "en-US" 5]
    Then Compare Parameter ["x-vf-trace-network-bearer" "4G" 5]
    Then Compare Parameter ["x-vf-trace-os-name" "Windows" 5]
    Then Compare Parameter ["x-vf-trace-os-version" "NT 4.0" 5]
    Then Compare Parameter ["x-vf-trace-mcc" "NA" 5]
    Then Compare Parameter ["x-vf-trace-mnc" "NA" 5]
    Then Compare Parameter ["x-vf-trace-platform" "JS" 5]
