Feature: check AppLaunch event

  Background: User Opens App and Capture Events
    When Capture IOS Events
#    Then Pause Time "3000" ms

  Scenario: Check 1st App Launch Event
    Then Validate IOS Element ["event-description" "App launched"] for event ["Application" "NA"]
#    Then Check Element existed ["x-vf-trace-transaction-id" 0]
#    Then Check Element value ["x-vf-trace-tid" "NA" 0]
#    Then Check Element value ["event-description" "App launched" 0]
#    Then Check Element existed ["x-vf-trace-timestamp" 0]
#    Then Check Element value ["event-element" "NA" 0]
#    Then Check Element value ["x-vf-net-type" "WiFi" 0]
#    Then Check Element value ["event-type" "Application" 0]
#    Then Check Element value ["x-vf-user-id" "NA" 0]
#    Then Check Element value ["x-vf-net-band" "NA" 0]
#    Then Check Element value ["device-orientation" "Portrait" 0]
#    Then Check Element value ["page-name" "Main Page VC" 0]
#    Then Check Element value ["subpage-name" "NA" 0]
#    Then Check Element existed ["x-vf-trace-session-id" 0]
#    Then Check Element value ["x-vf-app-state" "Foreground" 0]

  Scenario: Check 2nd App Launch Event
    Then Check Element existed ["x-vf-trace-transaction-id" 1]
    Then Check Element value ["x-vf-net-band" "NA" 1]
    Then Check Element value ["x-vf-net-type" "WiFi" 1]
    Then Check Element value ["subpage-name" "NA" 1]
    Then Check Element existed ["x-vf-trace-timestamp" 1]
    Then Check Element value ["event-element" "App Launch" 1]
    Then Check Element existed ["x-vf-trace-session-id" 1]
    Then Check Element value ["x-vf-trace-tid" "NA" 1]
    Then Check Element value ["x-vf-user-id" "NA" 1]
    Then Check Element value ["x-vf-app-state" "Foreground" 1]
    Then Check Element existed ["event-description" 1]
    Then Check Element value ["page-name" "Main Page VC" 1]
    Then Check Element value ["event-type" "Application" 1]
    Then Check Element value ["device-orientation" "Portrait" 1]

  Scenario: Check 3rd App Launch Event
    Then Check Element existed ["x-vf-trace-timestamp" 2]
    Then Check Element existed ["event-description" 2]
    Then Check Element existed ["x-vf-net-type" 2]
    Then Check Element value ["event-element" "Component" 2]
    Then Check Element existed ["x-vf-trace-session-id" 2]
    Then Check Element value ["event-type" "UICustom" 2]
    Then Check Element value ["x-vf-net-band" "NA" 2]
    Then Check Element value ["x-vf-user-id" "NA" 2]
    Then Check Element value ["x-vf-trace-tid" "NA" 2]
    Then Check Element value ["page-name" "Main Page VC" 2]
    Then Check Element value ["x-vf-app-state" "Foreground" 2]
    Then Check Element value ["device-orientation" "Portrait" 2]
    Then Check Element existed ["x-vf-trace-transaction-id" 2]
    Then Check Element value ["subpage-name" "NA" 2]

  Scenario: Check 4th App Launch Event
    Then Check Element value ["x-vf-user-id" "NA" 3]
    Then Check Element value ["event-element" "NA" 3]
    Then Check Element value ["x-vf-net-band" "NA" 3]
    Then Check Element existed ["x-vf-trace-timestamp" 3]
    Then Check Element value ["x-vf-app-state" "Foreground" 3]
    Then Check Element value ["event-type" "Application" 3]
    Then Check Element value ["event-description" "Application enters foreground" 3]
    Then Check Element value ["subpage-name" "NA" 3]
    Then Check Element value ["x-vf-net-type" "WiFi" 3]
    Then Check Element value ["page-name" "Main Page VC" 3]
    Then Check Element existed ["x-vf-trace-transaction-id" 3]
    Then Check Element value ["x-vf-trace-tid" "NA" 3]
    Then Check Element value ["device-orientation" "Portrait" 3]
    Then Check Element existed ["x-vf-trace-session-id" 3]

  Scenario: Check 5th App Launch Event
    Then Check Element existed ["x-vf-trace-transaction-id" 4]
    Then Check Element value ["x-vf-trace-tid" "NA" 4]
    Then Check Element value ["x-vf-net-band" "NA" 4]
    Then Check Element value ["page-name" "UINavigationController" 4]
    Then Check Element value ["event-element" "Load Time" 4]
    Then Check Element existed ["x-vf-trace-timestamp" 4]
    Then Check Element value ["x-vf-net-type" "WiFi" 4]
    Then Check Element value ["x-vf-user-id" "NA" 4]
    Then Check Element value ["x-vf-app-state" "Foreground" 4]
    Then Check Element value ["device-orientation" "Portrait" 4]
    Then Check Element existed ["x-vf-trace-session-id" 4]
    Then Check Element value ["subpage-name" "NA" 4]
    Then Check Element existed ["event-description" 4]
    Then Check Element value ["event-type" "Page" 4]

  Scenario: Check 6th App Launch Event
    Then Check Element existed ["x-vf-trace-session-id" 5]
    Then Check Element existed ["x-vf-trace-transaction-id" 5]
    Then Check Element value ["x-vf-net-type" "WiFi" 5]
    Then Check Element value ["x-vf-trace-tid" "NA" 5]
    Then Check Element value ["event-type" "Page" 5]
    Then Check Element value ["subpage-name" "NA" 5]
    Then Check Element value ["x-vf-user-id" "NA" 5]
    Then Check Element value ["page-name" "Main Page VC" 5]
    Then Check Element value ["device-orientation" "Portrait" 5]
    Then Check Element value ["x-vf-app-state" "Foreground" 5]
    Then Check Element value ["x-vf-net-band" "NA" 5]
    Then Check Element existed ["x-vf-trace-timestamp" 5]
    Then Check Element value ["event-element" "Load Time" 5]
    Then Check Element existed ["event-description" 5]