Feature: check AppLaunch event

  Background: User Opens App and Capture Events
    When Capture IOS Events
#    Then Pause Time "3000" ms

  Scenario: Check 1st App Launch Event
    Then Validate IOS Element ["event-description" "App launched"] for event ["Application" "NA"]
    Then Validate IOS Element ["x-vf-trace-transaction-id" "SMAPI_Presence"] for event ["Application" "NA"]
    Then Validate IOS Element ["x-vf-trace-tid" "NA"] for event ["Application" "NA"]
    Then Validate IOS Element ["event-description" "App launched"] for event ["Application" "NA"]
    Then Validate IOS Element ["x-vf-trace-timestamp" "SMAPI_Presence"] for event ["Application" "NA"]
#    Then Validate IOS Element ["event-element" "NA"] for event ["Application" "NA"]
    Then Validate IOS Element ["x-vf-net-type" "WiFi"] for event ["Application" "NA"]
#    Then Validate IOS Element ["event-type" "Application"] for event ["Application" "NA"]
    Then Validate IOS Element ["x-vf-user-id" "NA"] for event ["Application" "NA"]
    Then Validate IOS Element ["x-vf-net-band" "NA"] for event ["Application" "NA"]
    Then Validate IOS Element ["device-orientation" "Portrait"] for event ["Application" "NA"]
    Then Validate IOS Element ["page-name" "Main Page VC"] for event ["Application" "NA"]
    Then Validate IOS Element ["subpage-name" "NA"] for event ["Application" "NA"]
    Then Validate IOS Element ["x-vf-trace-session-id" "SMAPI_Presence"] for event ["Application" "NA"]
    Then Validate IOS Element ["x-vf-app-state" "Foreground"] for event ["Application" "NA"]

  Scenario: Check 2nd App Launch Event
    Then Validate IOS Element ["x-vf-trace-transaction-id" "SMAPI_Presence"] for event ["Application" "App Launch"]
    Then Validate IOS Element ["x-vf-net-band" "NA"] for event ["Application" "App Launch"]
    Then Validate IOS Element ["x-vf-net-type" "WiFi"] for event ["Application" "App Launch"]
    Then Validate IOS Element ["subpage-name" "NA"] for event ["Application" "App Launch"]
    Then Validate IOS Element ["x-vf-trace-timestamp" "SMAPI_Presence"] for event ["Application" "App Launch"]
#    Then Validate IOS Element ["event-element" "App Launch"] for event ["Application" "NA"]
    Then Validate IOS Element ["x-vf-trace-session-id" "SMAPI_Presence"] for event ["Application" "App Launch"]
    Then Validate IOS Element ["x-vf-trace-tid" "NA"] for event ["Application" "App Launch"]
    Then Validate IOS Element ["x-vf-user-id" "NA"] for event ["Application" "App Launch"]
    Then Validate IOS Element ["x-vf-app-state" "Foreground"] for event ["Application" "App Launch"]
    Then Validate IOS Element ["event-description" "SMAPI_Presence"] for event ["Application" "App Launch"]
    Then Validate IOS Element ["page-name" "Main Page VC"] for event ["Application" "App Launch"]
#    Then Validate IOS Element ["event-type" "Application"] for event ["Application" "NA"]
    Then Validate IOS Element ["device-orientation" "Portrait"] for event ["Application" "App Launch"]

  Scenario: Check 3rd App Launch Event
    Then Validate IOS Element ["x-vf-trace-timestamp" "SMAPI_Presence"] for event ["UICustom" "Component"]
    Then Validate IOS Element ["event-description" "SMAPI_Presence"] for event ["UICustom" "Component"]
    Then Validate IOS Element ["x-vf-net-type" "SMAPI_Presence"] for event ["UICustom" "Component"]
#    Then Validate IOS Element ["event-element" "Component"] for event ["Application" "NA"]
    Then Validate IOS Element ["x-vf-trace-session-id" "SMAPI_Presence"] for event ["UICustom" "Component"]
#    Then Validate IOS Element ["event-type" "UICustom"] for event ["Application" "NA"]
    Then Validate IOS Element ["x-vf-net-band" "NA"] for event ["UICustom" "Component"]
    Then Validate IOS Element ["x-vf-user-id" "NA"] for event ["UICustom" "Component"]
    Then Validate IOS Element ["x-vf-trace-tid" "NA"] for event ["UICustom" "Component"]
    Then Validate IOS Element ["page-name" "Main Page VC"] for event ["UICustom" "Component"]
    Then Validate IOS Element ["x-vf-app-state" "Foreground"] for event ["UICustom" "Component"]
    Then Validate IOS Element ["device-orientation" "Portrait"] for event ["UICustom" "Component"]
    Then Validate IOS Element ["x-vf-trace-transaction-id" "SMAPI_Presence"] for event ["UICustom" "Component"]
    Then Validate IOS Element ["subpage-name" "NA"] for event ["UICustom" "Component"]

  Scenario: Check 4th App Launch Event
    Then Validate IOS Element ["x-vf-user-id" "NA"] for event ["Application" "NA"]
#    Then Validate IOS Element ["event-element" "NA"] for event ["Application" "NA"]
    Then Validate IOS Element ["x-vf-net-band" "NA"] for event ["Application" "NA"]
    Then Validate IOS Element ["x-vf-trace-timestamp" "SMAPI_Presence"] for event ["Application" "NA"]
    Then Validate IOS Element ["x-vf-app-state" "Foreground"] for event ["Application" "NA"]
#    Then Validate IOS Element ["event-type" "Application"] for event ["Application" "NA"]
    Then Validate IOS Element ["event-description" "Application enters foreground"] for event ["Application" "NA"]
    Then Validate IOS Element ["subpage-name" "NA"] for event ["Application" "NA"]
    Then Validate IOS Element ["x-vf-net-type" "WiFi"] for event ["Application" "NA"]
    Then Validate IOS Element ["page-name" "Main Page VC"] for event ["Application" "NA"]
    Then Validate IOS Element ["x-vf-trace-transaction-id" "SMAPI_Presence"] for event ["Application" "NA"]
    Then Validate IOS Element ["x-vf-trace-tid" "NA"] for event ["Application" "NA"]
    Then Validate IOS Element ["device-orientation" "Portrait"] for event ["Application" "NA"]
    Then Validate IOS Element ["x-vf-trace-session-id" "SMAPI_Presence"] for event ["Application" "NA"]

  Scenario: Check 5th App Launch Event
    Then Validate IOS Element ["x-vf-trace-transaction-id" "SMAPI_Presence"] for event ["Page" "Load Time"]
    Then Validate IOS Element ["x-vf-trace-tid" "NA"] for event ["Page" "Load Time"]
    Then Validate IOS Element ["x-vf-net-band" "NA"] for event ["Page" "Load Time"]
    Then Validate IOS Element ["page-name" "UINavigationController"] for event ["Page" "Load Time"]
#    Then Validate IOS Element ["event-element" "Load Time"] for event ["Application" "NA"]
    Then Validate IOS Element ["x-vf-trace-timestamp" "SMAPI_Presence"] for event ["Page" "Load Time"]
    Then Validate IOS Element ["x-vf-net-type" "WiFi"] for event ["Page" "Load Time"]
    Then Validate IOS Element ["x-vf-user-id" "NA"] for event ["Page" "Load Time"]
    Then Validate IOS Element ["x-vf-app-state" "Foreground"] for event ["Page" "Load Time"]
    Then Validate IOS Element ["device-orientation" "Portrait"] for event ["Page" "Load Time"]
    Then Validate IOS Element ["x-vf-trace-session-id" "SMAPI_Presence"] for event ["Page" "Load Time"]
    Then Validate IOS Element ["subpage-name" "NA"] for event ["Page" "Load Time"]
    Then Validate IOS Element ["event-description" "SMAPI_Presence"] for event ["Page" "Load Time"]
#    Then Validate IOS Element ["event-type" "Page"] for event ["Application" "NA"]

  Scenario: Check 6th App Launch Event
    Then Validate IOS Element ["x-vf-trace-session-id" "SMAPI_Presence"] for event ["Page" "Load Time"]
    Then Validate IOS Element ["x-vf-trace-transaction-id" "SMAPI_Presence"] for event ["Page" "Load Time"]
    Then Validate IOS Element ["x-vf-net-type" "WiFi"] for event ["Page" "Load Time"]
    Then Validate IOS Element ["x-vf-trace-tid" "NA"] for event ["Page" "Load Time"]
#    Then Validate IOS Element ["event-type" "Page"] for event ["Application" "NA"]
    Then Validate IOS Element ["subpage-name" "NA"] for event ["Page" "Load Time"]
    Then Validate IOS Element ["x-vf-user-id" "NA"] for event ["Page" "Load Time"]
    Then Validate IOS Element ["page-name" "Main Page VC"] for event ["Page" "Load Time"]
    Then Validate IOS Element ["device-orientation" "Portrait"] for event ["Page" "Load Time"]
    Then Validate IOS Element ["x-vf-app-state" "Foreground"] for event ["Page" "Load Time"]
    Then Validate IOS Element ["x-vf-net-band" "NA"] for event ["Page" "Load Time"]
    Then Validate IOS Element ["x-vf-trace-timestamp" "SMAPI_Presence"] for event ["Page" "Load Time"]
#    Then Validate IOS Element ["event-element" "Load Time"] for event ["Application" "NA"]
    Then Validate IOS Element ["event-description" "SMAPI_Presence"] for event ["Page" "Load Time"]